name: Build depedencies

on: [push]

jobs:
  build-win64:
    if: false
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install via vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg build/vcpkg
          ./build/vcpkg/bootstrap-vcpkg.bat
          ./build/vcpkg/vcpkg install configcat --triplet x64-windows

      - uses: actions/upload-artifact@v3
        with:
          name: Win64
          path: ./build/vcpkg/packages/*/lib/*

  build-android:
    if: false
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install via vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg build/vcpkg
          ./build/vcpkg/bootstrap-vcpkg.bat
          ./build/vcpkg/vcpkg install configcat --triplet arm64-android

      - uses: actions/upload-artifact@v3
        with:
          name: Android
          path: ./build/vcpkg/packages/*/lib/*

  build-macos:
    if: false
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install via vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg build/vcpkg
          ./build/vcpkg/bootstrap-vcpkg.sh
          ./build/vcpkg/vcpkg install configcat --triplet x64-osx

      - uses: actions/upload-artifact@v3
        with:
          name: MacOs
          path: ./build/vcpkg/packages/*/lib/*

  build-ios:
    if: false
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install via vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg build/vcpkg
          ./build/vcpkg/bootstrap-vcpkg.sh
          ./build/vcpkg/vcpkg install configcat --triplet arm64-ios

      - uses: actions/upload-artifact@v3
        with:
          name: iOS
          path: ./build/vcpkg/packages/*/lib/*

  build-linux:
    if: true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install via vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg build/vcpkg
          ./build/vcpkg/bootstrap-vcpkg.sh

          # Extra steps for Unreal Engine integration
          # cp "$GITHUB_WORKSPACE/Extras/triplets/x64-linux-unreal.cmake" "./build/vcpkg/triplets/x64-linux-unreal.cmake"
          export CC=clang
          export CXX=clang++

          ./build/vcpkg/vcpkg install configcat --triplet x64-linux-unreal --overlay-triplets "$GITHUB_WORKSPACE/Extras/triplets"

      - uses: actions/upload-artifact@v3
        with:
          name: Linux
          path: ./build/vcpkg/packages/*/lib/*